spring:
  ai:
    openai:
      api-key: ${OPEN_CODE_KEY}
      base-url: https://opencode.ai/zen/go/v1
      chat:
        model: mimo-v2.5
        temperature: 0.2
    mcp:
      client:
        enabled: true
        stdio:
          connections:
            elasticsearch:
              command: uvx
              args:
                - "elasticsearch-mcp-server"
              env:
                ELASTICSEARCH_URL: http://10.13.37.154:9200
                ELASTICSEARCH_USERNAME:
                ELASTICSEARCH_PASSWORD: